"""Initial migration

Revision ID: 297e72539db0
Revises: 
Create Date: 2026-03-02 15:38:57.232983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297e72539db0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [c['name'] for c in inspector.get_columns('issue_labels')]

    if 'background' not in existing_columns:
        op.add_column('issue_labels', sa.Column('background', sa.Text(), nullable=True))
    if 'core_contentions' not in existing_columns:
        op.add_column('issue_labels', sa.Column('core_contentions', sa.Text(), nullable=True))
    if 'media_ratio' not in existing_columns:
        op.add_column('issue_labels', sa.Column('media_ratio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_labels', 'media_ratio')
    op.drop_column('issue_labels', 'core_contentions')
    op.drop_column('issue_labels', 'background')
    # ### end Alembic commands ###
