"""Add status column to IssueLabel

Revision ID: 7032c6f74df4
Revises: 7a348029bd1f
Create Date: 2026-05-16 16:27:08.225047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7032c6f74df4'
down_revision: Union[str, None] = '7a348029bd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_labels', sa.Column('status', sa.String(length=20), server_default='analyzing', nullable=True))
    op.create_index(op.f('ix_issue_labels_status'), 'issue_labels', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_labels_status'), table_name='issue_labels')
    op.drop_column('issue_labels', 'status')
    # ### end Alembic commands ###
