"""Add article_type and issue_type

Revision ID: 7a348029bd1f
Revises: a794dfe625ff
Create Date: 2026-05-03 22:48:59.536389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a348029bd1f'
down_revision: Union[str, None] = 'a794dfe625ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_type', sa.String(), server_default='editorial', nullable=False))
    op.add_column('issue_labels', sa.Column('issue_type', sa.String(), server_default='editorial', nullable=False))
    op.drop_column('issue_labels', 'media_ratio')
    op.drop_column('issue_labels', 'core_contentions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_labels', sa.Column('core_contentions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('issue_labels', sa.Column('media_ratio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('issue_labels', 'issue_type')
    op.drop_column('articles', 'article_type')
    # ### end Alembic commands ###
