"""add_conflict_summary_to_issuelabel

Revision ID: a46a4bee7856
Revises: bd6e7137ea4c
Create Date: 2026-03-20 23:38:59.593067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a46a4bee7856'
down_revision: Union[str, None] = 'bd6e7137ea4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_logs_id', table_name='execution_logs')
    op.drop_index('ix_execution_logs_job_type', table_name='execution_logs')
    op.drop_index('ix_execution_logs_status', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.add_column('issue_labels', sa.Column('conflict_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_labels', 'conflict_summary')
    op.create_table('execution_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='execution_logs_pkey')
    )
    op.create_index('ix_execution_logs_status', 'execution_logs', ['status'], unique=False)
    op.create_index('ix_execution_logs_job_type', 'execution_logs', ['job_type'], unique=False)
    op.create_index('ix_execution_logs_id', 'execution_logs', ['id'], unique=False)
    # ### end Alembic commands ###
