"""cleanup_user_provider_columns

Revision ID: a794dfe625ff
Revises: a794dfe625fe
Create Date: 2026-03-30 11:27:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a794dfe625ff'
down_revision: Union[str, None] = 'a794dfe625fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # users 테이블에서 더 이상 사용하지 않는 레거시 컬럼 삭제
    op.drop_column('users', 'provider')
    op.drop_column('users', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
