"""check_prod_drift

Revision ID: a794dfe625fe
Revises: a46a4bee7856
Create Date: 2026-03-26 12:53:16.528896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a794dfe625fe'
down_revision: Union[str, None] = 'a46a4bee7856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 컬럼 존재 여부 체크 (PostgreSQL용)
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='users' AND column_name='draft_issue_ids'"))
    if not res.fetchone():
        op.add_column('users', sa.Column('draft_issue_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'draft_issue_ids')
    # ### end Alembic commands ###
