"""cleanup_user_provider_columns

Revision ID: a794dfe625ff
Revises: a794dfe625fe
Create Date: 2026-03-30 11:27:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a794dfe625ff'
down_revision: Union[str, None] = 'a794dfe625fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 컬럼 삭제 (PostgreSQL의 IF EXISTS 구문 사용으로 더욱 안전하게 처리)
    op.execute(sa.text("ALTER TABLE users DROP COLUMN IF EXISTS provider"))
    op.execute(sa.text("ALTER TABLE users DROP COLUMN IF EXISTS provider_id"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
