"""check_prod_drift

Revision ID: a794dfe625fe
Revises: a46a4bee7856
Create Date: 2026-03-26 12:53:16.528896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a794dfe625fe'
down_revision: Union[str, None] = 'a46a4bee7856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 컬럼 존재 여부 체크 후 추가 (PostgreSQL의 IF NOT EXISTS 구문 사용)
    op.execute(sa.text("ALTER TABLE users ADD COLUMN IF NOT EXISTS draft_issue_ids INTEGER[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'draft_issue_ids')
    # ### end Alembic commands ###
