"""Add pre_generated_draft

Revision ID: bd6e7137ea4c
Revises: 7d570e08f92b
Create Date: 2026-03-02 20:03:33.743130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd6e7137ea4c'
down_revision: Union[str, None] = '7d570e08f92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'execution_logs' not in tables:
        op.create_table('execution_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('mode', sa.String(), nullable=True),
        sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('logs', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
        op.create_index(op.f('ix_execution_logs_job_type'), 'execution_logs', ['job_type'], unique=False)
        op.create_index(op.f('ix_execution_logs_status'), 'execution_logs', ['status'], unique=False)

    if 'system_settings' not in tables:
        op.create_table('system_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('llm_mode', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)

    if 'social_accounts' not in tables:
        op.create_table('social_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('provider_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    # 'issue_labels' 테이블에 'pre_generated_draft' 컬럼이 이미 있는지 확인
    columns = [c['name'] for c in inspector.get_columns('issue_labels')]
    if 'pre_generated_draft' not in columns:
        op.add_column('issue_labels', sa.Column('pre_generated_draft', sa.Text(), nullable=True))
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('issue_labels', 'pre_generated_draft')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_execution_logs_status'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_job_type'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    # ### end Alembic commands ###
